//
// Created by jasf on 5/14/16.
//

#ifndef VIRTUALMEMORYMANAGER_DEFINES_H
#define VIRTUALMEMORYMANAGER_DEFINES_H

#define MAX_OCUPACAO 9
#define OCUPACAO_OK 8
#define NUMERO_FRAMES 10

#define QUANTIDADE_USR_PROCESSES 1

//in unites of microsecond [10^4 usec = 0.01 sec]
#define PAGE_SUBS_SLEEP_TIME 10000


#define INT_SIZE 4
#define LONG_SIZE 4


#define MAX_LONG 0x7FFFFFFFFFFFFFFFL
#define MAX_INT 0x7FFFFFFF

#define MAX_NUMERO_PROCESSOS 1024

//10 ms
#define USER_USLEEP_TIPE 10000

#endif //VIRTUALMEMORYMANAGER_DEFINES_H
